try {
  throw Error('This error will be caught');
} catch (e) {
    console.log(e);
}
